### ISSUE TITLE
Measure Li-Ion battery decharge curve

### ISSUE THREAD

**Issue by MeierTobias** [guidosch/bikecounter#18]
- [ ] Measure the decharge curve
- [ ] Calculate polynomial coeff.

**Comment by guidosch** [comment]
Decharge curve of the "antennentrail-1" device over summer period 2022.

<img width="1110" alt="Bildschirmfoto 2022-10-15 um 11 57 25" src="https://user-images.githubusercontent.com/3204954/195980986-058e6cba-f16e-4fef-b6e6-319777b7d976.png">

**Comment by guidosch** [comment]
Mapping from value to charging level: Ideas
https://stackoverflow.com/questions/13399821/data-structures-that-can-map-a-range-of-keys-to-a-value
https://greensock.com/docs/v3/GSAP/UtilityMethods/mapRange()
