### ISSUE TITLE
Implement Lora downlink

### ISSUE THREAD

**Issue by MeierTobias** [guidosch/bikecounter#24]
- ensures that the message was transmitted
- pass configuration to device

**Comment by guidosch** [comment]
Idea is to use the downlink to check if the message was received by any gateway. If the device does not receive a "ACK" it will retry a few times (not endless du to battery drain).

May collect failed messages as counter and add to health data to get a idea how many times it does not work. Could also be determined by the msg. send intervall...

**Comment by MeierTobias** [comment]
modem.endPacket(true);

**Comment by MeierTobias** [comment]
I tested and implemented the modem.endPacket(true); method into the pro version.
It works well but I saw some uplink messages which were sent in a very short time span (20 sec.) I want to check if this has something to do with the "ACK" downlink

**Comment by MeierTobias** [comment]
implemented and tested with #48
