### ISSUE TITLE
Round battery voltage to calm down graph

### ISSUE THREAD

**Issue by guidosch** [guidosch/bikecounter#79]
The voltage level toggels between some micro levels which makes the graph unreadable.

<img width="676" alt="Bildschirm­foto 2023-01-22 um 18 21 24" src="https://user-images.githubusercontent.com/3204954/213930290-c0082575-62ae-40f3-97d1-3169da1ce8a6.png">

**Comment by MeierTobias** [comment]
I would suggest to keep as much information as possible in the database for future debugging issues. (Also a voltage step discretization of less than 0.1V is necessary to determine the battery level.)

One possible solution would be to adjust the graph scales to a fix range. 
- Bat. volt. 3V - 4.2V
- Bat. level 0% - 100%) 

I think this would tidy up the graph enough to make it better readable.

**Comment by guidosch** [comment]
Scaltes to fixed range did the trick.
